extends@:
    type: default

form:
  validation: loose

  fields:

    tabs:
      type: tabs      
      active: 1

      fields:
        content:
          type: tab
          ordering@: 0
          title: PLUGIN_ADMIN.CONTENT

          fields:
            header.title:
              replace@: true
                
              type: text
              autofocus: false
              style: vertical
              label: PLUGIN_ADMIN.TITLE

            content:
              type: studioeditor
              autofocus: false
              validate:
                type: textarea
            
            uploads:
              type: studiopagemedia
              label: PLUGIN_ADMIN.PAGE_MEDIA
              accept:
                - image/*
                - video/*
                - application/zip
                - application/pdf
            
            frontmatter:
                unset@: true
                
            header.media_order:
                unset@: true

            header.resizeall:
              replace@: true
              type: studiodefaulttoggle
              name: resizeall
              label: PLUGIN_STUDIOEDITOR.PAGE_RESIZE_IMAGES
              help: PLUGIN_STUDIOEDITOR.PAGE_RESIZE_IMAGES_HINT
              highlight: 0
              default: 0
              validate:
                type: bool
              options:
                1: PLUGIN_STUDIOEDITOR.YES
                0: PLUGIN_STUDIOEDITOR.NO


        help:
          type: tab
          ordering@: 6
          title: Help
          fields:
            helpone:
              type: display
              size: large
              label: PLUGIN_STUDIOEDITOR.TAB_HELP_EDITOR_01_LABEL
              markdown: true
              content: PLUGIN_STUDIOEDITOR.TAB_HELP_EDITOR_01_CONTENT
            helptwo:
              type: display
              size: large
              label: PLUGIN_STUDIOEDITOR.TAB_HELP_EDITOR_02_LABEL
              markdown: true
              content: PLUGIN_STUDIOEDITOR.TAB_HELP_EDITOR_02_CONTENT
            helpthree:
              type: display
              size: large
              label: PLUGIN_STUDIOEDITOR.TAB_HELP_EDITOR_03_LABEL
              markdown: true
              content: PLUGIN_STUDIOEDITOR.TAB_HELP_EDITOR_03_CONTENT

        security:
          ordering@: 7


